// Generated by gencpp from file hog_haar_person_detection/BoundingBox.msg
// DO NOT EDIT!


#ifndef HOG_HAAR_PERSON_DETECTION_MESSAGE_BOUNDINGBOX_H
#define HOG_HAAR_PERSON_DETECTION_MESSAGE_BOUNDINGBOX_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace hog_haar_person_detection
{
template <class ContainerAllocator>
struct BoundingBox_
{
  typedef BoundingBox_<ContainerAllocator> Type;

  BoundingBox_()
    : center()
    , width(0)
    , height(0)  {
    }
  BoundingBox_(const ContainerAllocator& _alloc)
    : center(_alloc)
    , width(0)
    , height(0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _center_type;
  _center_type center;

   typedef uint32_t _width_type;
  _width_type width;

   typedef uint32_t _height_type;
  _height_type height;





  typedef boost::shared_ptr< ::hog_haar_person_detection::BoundingBox_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hog_haar_person_detection::BoundingBox_<ContainerAllocator> const> ConstPtr;

}; // struct BoundingBox_

typedef ::hog_haar_person_detection::BoundingBox_<std::allocator<void> > BoundingBox;

typedef boost::shared_ptr< ::hog_haar_person_detection::BoundingBox > BoundingBoxPtr;
typedef boost::shared_ptr< ::hog_haar_person_detection::BoundingBox const> BoundingBoxConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hog_haar_person_detection::BoundingBox_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hog_haar_person_detection::BoundingBox_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hog_haar_person_detection::BoundingBox_<ContainerAllocator1> & lhs, const ::hog_haar_person_detection::BoundingBox_<ContainerAllocator2> & rhs)
{
  return lhs.center == rhs.center &&
    lhs.width == rhs.width &&
    lhs.height == rhs.height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hog_haar_person_detection::BoundingBox_<ContainerAllocator1> & lhs, const ::hog_haar_person_detection::BoundingBox_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hog_haar_person_detection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hog_haar_person_detection::BoundingBox_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hog_haar_person_detection::BoundingBox_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hog_haar_person_detection::BoundingBox_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hog_haar_person_detection::BoundingBox_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hog_haar_person_detection::BoundingBox_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hog_haar_person_detection::BoundingBox_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hog_haar_person_detection::BoundingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "848ee5efc3139d88c5674f66671d9625";
  }

  static const char* value(const ::hog_haar_person_detection::BoundingBox_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x848ee5efc3139d88ULL;
  static const uint64_t static_value2 = 0xc5674f66671d9625ULL;
};

template<class ContainerAllocator>
struct DataType< ::hog_haar_person_detection::BoundingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hog_haar_person_detection/BoundingBox";
  }

  static const char* value(const ::hog_haar_person_detection::BoundingBox_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hog_haar_person_detection::BoundingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point center\n"
"uint32 width\n"
"uint32 height\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::hog_haar_person_detection::BoundingBox_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hog_haar_person_detection::BoundingBox_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.center);
      stream.next(m.width);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoundingBox_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hog_haar_person_detection::BoundingBox_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hog_haar_person_detection::BoundingBox_<ContainerAllocator>& v)
  {
    s << indent << "center: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.center);
    s << indent << "width: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HOG_HAAR_PERSON_DETECTION_MESSAGE_BOUNDINGBOX_H
